language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install libgoogle-perftools-dev google-perftools

compiler:
  - gcc

script:
  - cd ${TRAVIS_BUILD_DIR}
  - uname -a
  - free -m
  - w
  - pwd
  - ls -l
  - mkdir build
  - cd build
  - bash ../test/run_all_tests_for_all_interceptions.sh
