language: cpp
os: linux       # Jobs are on Linux unless specified otherwise
dist: trusty    # Jobs are on Trusty unless specified otherwise
sudo: false

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

install:
  - sudo apt-get install libgoogle-perftools-dev google-perftools
  - which ${CXX}
  - ${CXX} --version

before_install:
    - eval "${MATRIX_EVAL}"

compiler:
  - gcc

script:
  - uname -a
  - free -m
  - w
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - ls -l
  - mkdir build
  - cd build
  - bash ../test/run_all_tests_for_all_interceptions.sh
